// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thpdlrhpodjysrfsokqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRocGRscmhwb2RqeXNyZnNva3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODYyMjEsImV4cCI6MjA3MzM2MjIyMX0.0G6sP1a8DtFH2Ze5hhqWSF6l1veLW-GeSzpOKpmXLlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});